### ISSUE TITLE
Editor should validate pages on loading (was How should editor and api handle invalid regions and sections?)

### ISSUE THREAD

**Issue by sy238-unikent** [unikent/astro#168]
See below for requirements: https://github.com/unikent/astro/issues/168#issuecomment-350256186 

Use case: a breaking change is made to a region / section / layout definition without changing the version number.

Any existing pages may cause issues in the editor, and will be rejected when resaving in the API.

The user themselves cannot reorder or remove sections in the editor, so their only option would be to delete the page.

Should the editor check page validity on load?

Should the editor attempt to fix invalid pages on loading them?

**Comment by theninja** [comment]
Maybe this is more of an issue surrounding tooling, as we don't want to ever make a breaking change without changing the version number. Some kind of automated check which can tell us if it's a breaking change or not?

If the tooling doesn't allow for this then I feel this should as non-destructive as possible. Imagine a scenario where something is accidentally changed and not noticed immediately, then publishers would open the file and lose some of their data before the issue is corrected/reversed (it's too late though, as the data is now missing).

**Comment by sy238-unikent** [comment]
I'm not sure if implementing an automated check is worth the time and effort right now.

Users would still have their old data in the previous revisions, however as we don't yet have the functionality to view / revert these that's of limited use.

Saving currently rejects pages with invalid regions or sections, which includes both regions and sections that should not be there as well as regions with missing sections.

Perhaps the API should check page data -> region -> section validity on load, and if any regions or sections are missing, then if possible, silently add them to the page?

If unable to fix them automatically, show an appropriate error and refuse to allow editing that page further?

**Comment by samyapp** [comment]
Desired behaviour is that editor validates each page on loading it.

If there are any missing regions or sections it should alert the user and disable editing of the page.

Reasoning is that this is an exceptional condition (data is not in the correct format, most likely due to breaking changes in definition with versioning).

The editor should NOT attempt to fix any fixable (just missing regions) pages itself as it is more important to alert to the problem as other pages may also be broken in a non-fixable way.
